-- drop tables --
DROP TABLE CPU CASCADE CONSTRAINTS;
DROP TABLE CPU_PLACAMAE CASCADE CONSTRAINTS;
DROP TABLE MEMORIA CASCADE CONSTRAINTS;
DROP TABLE PC CASCADE CONSTRAINTS;
DROP TABLE PC_MEMORIA CASCADE CONSTRAINTS;
DROP TABLE PC_PLACAVIDEO CASCADE CONSTRAINTS;
DROP TABLE PLACAMAE CASCADE CONSTRAINTS;
DROP TABLE PLACAMAEMEMORIA CASCADE CONSTRAINTS;
DROP TABLE PLACAVIDEO CASCADE CONSTRAINTS;
DROP TABLE USUARIO CASCADE CONSTRAINTS;

-- drop sequences --

DROP SEQUENCE a_Usuario;
DROP SEQUENCE d_CPU;
DROP SEQUENCE e_Memoria;
DROP SEQUENCE f_PlacaVideo;
DROP SEQUENCE c_PlacaMae;
DROP SEQUENCE b_PC;
