-- USUARIO --
INSERT INTO "USR271"."USUARIO" (ID_CONTA, EMAIL, NOME) VALUES (a_Usuario.nextval, 'j.alves157@bol.com', 'Juliano Alves');
INSERT INTO "USR271"."USUARIO" (ID_CONTA, EMAIL, NOME) VALUES (a_Usuario.nextval, 'fernanda.ds1@gmail.com', 'Fernanda Souza');
INSERT INTO "USR271"."USUARIO" (ID_Conta, Email, nome) VALUES (a_Usuario.nextval,'rafael.santos@yahoo.com', 'Rafael Santos');
INSERT INTO "USR271"."USUARIO" (ID_Conta, Email, nome) VALUES (a_Usuario.nextval,'jesualdo_silva@uol.com', 'Jesualdo Silva');
INSERT INTO "USR271"."USUARIO" (ID_Conta, Email, nome) VALUES (a_Usuario.nextval,'lorrayne_kconceicao@uol.com', 'Lorrayne Katiussia Conceicao');

-- PLACAMAE --
INSERT INTO "USR271"."PLACAMAE" (ID_PLACAMAE, NOME, MODELO, ARQUITETURA, SOQUETE, VALOR) VALUES (c_Placamae.nextval, 'H510', 'Gigabyte Asus H510', 'Intel', 'LGA1200', '577,90');
INSERT INTO "USR271"."PLACAMAE" (ID_PLACAMAE, NOME, MODELO, ARQUITETURA, SOQUETE, VALOR) VALUES (c_Placamae.nextval, 'B450', 'Gigabyte Aorus B450', 'AMD', 'AM4', '747,27');
INSERT INTO "USR271"."PLACAMAE" (ID_PLACAMAE, NOME, MODELO, ARQUITETURA, SOQUETE, VALOR) VALUES (c_Placamae.nextval, 'X399', 'ASROCK X399', 'AMD', 'TR4', '2121,94');
INSERT INTO "USR271"."PLACAMAE" (ID_PLACAMAE, NOME, MODELO, ARQUITETURA, SOQUETE, VALOR) VALUES (c_Placamae.nextval, 'B360M', 'Asus TUF B360M-Plus Gaming', 'Intel', 'LGA1151', '699,90');
INSERT INTO "USR271"."PLACAMAE" (ID_PLACAMAE, NOME, MODELO, ARQUITETURA, SOQUETE, VALOR) VALUES (c_Placamae.nextval, 'B560M', 'Gigabyte B560M Aorus Elite', 'Intel', 'LGA1200', '979,94');

-- CPU --
INSERT INTO "USR271"."CPU" (ID_CPU, MODELO, SOQUETE, ARQUITETURA, VALOR) VALUES (d_CPU.nextval, 'i3-10100F', 'LGA1200', 'Intel', '589,90');
INSERT INTO "USR271"."CPU" (ID_CPU, MODELO, SOQUETE, ARQUITETURA, VALOR) VALUES (d_CPU.nextval, 'i7-10700F', 'LGA1200', 'Intel', '1749,90');
INSERT INTO "USR271"."CPU" (ID_CPU, MODELO, SOQUETE, ARQUITETURA, VALOR) VALUES (d_CPU.nextval, 'i5-9600K', 'LGA1151', 'Intel', '1686,35');
INSERT INTO "USR271"."CPU" (ID_CPU, MODELO, SOQUETE, ARQUITETURA, VALOR) VALUES (d_CPU.nextval, 'Ryzen 5 5600X', 'AM4', 'AMD', '1799,90');
INSERT INTO "USR271"."CPU" (ID_CPU, MODELO, SOQUETE, ARQUITETURA, VALOR) VALUES (d_CPU.nextval, 'Ryzen 9 3900X', 'TR4', 'AMD', '4384,51');
INSERT INTO "USR271"."CPU" (ID_CPU, MODELO, SOQUETE, ARQUITETURA, VALOR) VALUES (d_CPU.nextval, 'i5-11400', 'LGA1200', 'Intel', '1379,90');
INSERT INTO "USR271"."CPU" (ID_CPU, MODELO, SOQUETE, ARQUITETURA, VALOR) VALUES (d_CPU.nextval, 'i3-9100', 'LGA1151', 'Intel', '1131,54');
INSERT INTO "USR271"."CPU" (ID_CPU, MODELO, SOQUETE, ARQUITETURA, VALOR) VALUES (d_CPU.nextval, 'Ryzen 7 5800X', 'AM4', 'AMD', '2528,90');
INSERT INTO "USR271"."CPU" (ID_CPU, MODELO, SOQUETE, ARQUITETURA, VALOR) VALUES (d_CPU.nextval, 'Ryzen 5 5600G', 'AM4', 'AMD', '1624,90');
INSERT INTO "USR271"."CPU" (ID_CPU, MODELO, SOQUETE, ARQUITETURA, VALOR) VALUES (d_CPU.nextval, 'i3-9100', 'LGA1151', 'Intel', '1131,54');
INSERT INTO "USR271"."CPU" (ID_CPU, MODELO, SOQUETE, ARQUITETURA, VALOR) VALUES (d_CPU.nextval, 'Ryzen Threadripper 1950X', 'TR4', 'AMD', '1131,54');


-- Memoria --
INSERT INTO "USR271"."MEMORIA" (ID_MEMORIA, NOME, CAPACIDADE, ARQUITETURA, VALOR) VALUES (e_Memoria.nextval, 'HyperX', '4GiB', 'DDR4', '280,22');
INSERT INTO "USR271"."MEMORIA" (ID_MEMORIA, NOME, CAPACIDADE, ARQUITETURA, VALOR) VALUES (e_Memoria.nextval, 'Kingston Fury', '8GiB', 'DDR4', '269,90');
INSERT INTO "USR271"."MEMORIA" (ID_MEMORIA, NOME, CAPACIDADE, ARQUITETURA, VALOR) VALUES (e_Memoria.nextval, 'Corsair Vengeance', '8GiB', 'DDR4', '229,90');
INSERT INTO "USR271"."MEMORIA" (ID_MEMORIA, NOME, CAPACIDADE, ARQUITETURA, VALOR) VALUES (e_Memoria.nextval, 'XPG Hunter', '16GiB', 'DDR4', '529,90');
INSERT INTO "USR271"."MEMORIA" (ID_MEMORIA, NOME, CAPACIDADE, ARQUITETURA, VALOR) VALUES (e_Memoria.nextval, 'Crucial Ballistix', '8GiB', 'DDR4', '289,90');
INSERT INTO "USR271"."MEMORIA" (ID_MEMORIA, NOME, CAPACIDADE, ARQUITETURA, VALOR) VALUES (e_Memoria.nextval, 'Husky', '8GiB', 'DDR4', '472,90');
INSERT INTO "USR271"."MEMORIA" (ID_MEMORIA, NOME, CAPACIDADE, ARQUITETURA, VALOR) VALUES (e_Memoria.nextval, 'Corsair Vengeance', '32GiB', 'DDR4', '1055,04');
INSERT INTO "USR271"."MEMORIA" (ID_MEMORIA, NOME, CAPACIDADE, ARQUITETURA, VALOR) VALUES (e_Memoria.nextval, 'Maxsun', '16GiB', 'DDR4', '480,90');
INSERT INTO "USR271"."MEMORIA" (ID_MEMORIA, NOME, CAPACIDADE, ARQUITETURA, VALOR) VALUES (e_Memoria.nextval, 'Team Group T-Force', '8GiB', 'DDR4', '199,91');

-- GPU --
INSERT INTO "USR271"."PLACAVIDEO" (ID_PLACAVIDEO, NOME, CAPACIDADE, VALOR) VALUES (f_PlacaVideo.nextval, 'Gigabyte GTX-1660 OC', '6Gib', '1799,82');
INSERT INTO "USR271"."PLACAVIDEO" (ID_PLACAVIDEO, NOME, CAPACIDADE, VALOR) VALUES (f_PlacaVideo.nextval, 'Gainward RTX-3080 Ti', '12Gib', '14649,82');
INSERT INTO "USR271"."PLACAVIDEO" (ID_PLACAVIDEO, NOME, CAPACIDADE, VALOR) VALUES (f_PlacaVideo.nextval, 'Radeon RX6600 XT', '8Gib', '4599,94');
INSERT INTO "USR271"."PLACAVIDEO" (ID_PLACAVIDEO, NOME, CAPACIDADE, VALOR) VALUES (f_PlacaVideo.nextval, 'GTX-1650 OC', '4Gib', '2099,82');
INSERT INTO "USR271"."PLACAVIDEO" (ID_PLACAVIDEO, NOME, CAPACIDADE, VALOR) VALUES (f_PlacaVideo.nextval, 'MSI GTX-1050 Ti', '4Gib', '1749,82');
INSERT INTO "USR271"."PLACAVIDEO" (ID_PLACAVIDEO, NOME, CAPACIDADE, VALOR) VALUES (f_PlacaVideo.nextval, 'Radeon RX 6800 XT', '16Gib', '10248,82');
INSERT INTO "USR271"."PLACAVIDEO" (ID_PLACAVIDEO, NOME, CAPACIDADE, VALOR) VALUES (f_PlacaVideo.nextval, 'Radeon RX 560', '4Gib', '2249,82');
INSERT INTO "USR271"."PLACAVIDEO" (ID_PLACAVIDEO, NOME, CAPACIDADE, VALOR) VALUES (f_PlacaVideo.nextval, 'Geforce GT710', '1Gib', '299,82');
INSERT INTO "USR271"."PLACAVIDEO" (ID_PLACAVIDEO, NOME, CAPACIDADE, VALOR) VALUES (f_PlacaVideo.nextval, 'Radeon RX 550', '4Gib', '1029,90');
INSERT INTO "USR271"."PLACAVIDEO" (ID_PLACAVIDEO, NOME, CAPACIDADE, VALOR) VALUES (f_PlacaVideo.nextval, 'Radeon R9 370', '4Gib', '1150,82');
